### ISSUE TITLE
英語の時は Alex あたりのネイティブに喋らせる

### ISSUE THREAD

**Issue by daicche** [re-born/say_queristory#1]
日本語と英語が混じってる時はどうしよう〜

**Comment by rooa** [comment]
ありそうなのはこんなものかな?

---

#### 1: スペース区切りでEN/JA切り替わってる場合

ex. `ios アプリ`
- `delimiter=' '` で区切った後,それぞれを[a-zA-Z0-9]とかで判別
  - `true` → Alex
  - `false` → Otoya

#### 2: 一単語にEN/JA両方入ってる場合

ex `iosアプリ 開発`
- mecabで切り分ける (mecabに判別機能はないかも)→ 1へ

**Comment by rooa** [comment]
mecabで日本語クエリまで切られちゃうか

**Comment by daicche** [comment]
ruby だと 正規表現の `\w` で英数字、 `\W` で 英数字以外(日本語とか)がマッチするみたい

**Comment by rooa** [comment]
まじか、

mecabで `'iosアプリ 開発' → ['ios', 'アプリ','開発']`みたいにした後正規表現で判定して、マッチしない隣接項はconcatするとできるかな、メンド。

**Comment by daicche** [comment]
正規表現で単語ごと(スペース区切りと日本語英語区切り)に配列にぶっ込んで
1単語ずつ喋らせると実装は楽だと思うけど、
sayコマンド何回も使うとインターバルが長くなるかも

**Comment by rooa** [comment]
だめだ、アプリと開発を分けられん。

そうだね

**Comment by daicche** [comment]
`iOSアプリ` みたいな英語と日本語がくっついてるクエリって
分けた方がいい場合とそうじゃない場合の両方ある気がする

**Comment by rooa** [comment]
`アイオーエス　アプリ` じゃなくて `アイオーエスアプリ` と読むべき、的な場合分け？

**Comment by daicche** [comment]
うん、`iOSアプリ` とか `id取得` みたいなのは喋らせてみたけど分けない方がよさそう

**Comment by rooa** [comment]
それはさすがにコンピュータ判別は無理そう

**Comment by daicche** [comment]
分けた方が良い(英語と日本語がくっついてて英語はネイティブ英語な発音の方がいい)場合ってあんまり無いような気もする。
あるとすれば `levenberg-marquardt法` とか `damerau-levenshtein距離` とか…？

**Comment by rooa** [comment]
必要だとは言ったけど、そんなネイティブの発音必要ないかな。ツイート見れば垂れ流しを注意深く聴いてクエリ判断する必要ないし。

**Comment by daicche** [comment]
全部英語だった場合にだけ ネイティブ勢に喋らせる？
